package com.rocket.summer.framework.expression.spel;

import com.rocket.summer.framework.expression.EvaluationContext;
import com.rocket.summer.framework.expression.EvaluationException;

/**
 * Base superclass for compiled expressions. Each generated compiled expression class
 * will extend this class and implement the {@link #getValue} method. It is not intended
 * to be subclassed by user code.
 *
 * @author Andy Clement
 * @since 4.1
 */
public abstract class CompiledExpression {

    /**
     * Subclasses of CompiledExpression generated by SpelCompiler will provide an
     * implementation of this method.
     */
    public abstract Object getValue(Object target, EvaluationContext context) throws EvaluationException;

}
